package coc.Tokens;

public class Tokens {
    private static final String API_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImYzOGRkZDE4LTU5ZTQtNGUzMy04NDY3LTUyZjMzOGNlZGMxZSIsImlhdCI6MTY4MjYzOTc4OSwic3ViIjoiZGV2ZWxvcGVyLzkwYjUyMDQ3LWYxNDUtMDRmNS01ZTQ5LWMwNTBhN2MxYzg1NiIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE3NC4xMDAuMTg4LjEyIl0sInR5cGUiOiJjbGllbnQifV19.Hzzhb7rFLURWliZOV_2vniRBn_-SmcHZsI9R_wTqF4Vx4bYV8LOLTBxCr41y3Kh8hEuSbz0cOFam6S-Rt34pnA";

    public static String getAPI_KEY () {
        return API_KEY;
    }
}
